version: "3.9"
services:
  eligibility-service:
    container_name: willem-eligibility-service
    build:
      dockerfile: .ops/docker/Dockerfile
      context: .
      target: dist
    restart: unless-stopped
    env_file:
      - .env
    environment:
      #This overrides the port specified in the .env file as is important to keep this at port 8080 for the sake of nginx.
      #Feel free to change this for running it locally.
      - HTTP_PORT=8080
#    ports:
#      - "8080:8080"

  swagger:
     container_name: willem-swagger
     image: swaggerapi/swagger-ui
     environment:
       - BASE_URL=/swagger
       - SWAGGER_JSON=/api-docs/swagger.json
#     ports:
#      - "8090:8080"
     volumes:
       - "./docs/swagger.json:/api-docs/swagger.json"

  nginx:
    image: nginx:latest
    container_name: willem-nginx
    ports:
     - "80:8081"
    volumes:
     - .ops/configs/nginx-service.conf:/etc/nginx/conf.d/nginx-service.conf
    links:
     - eligibility-service
     - swagger